version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    restart: always
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
